# Generated by Django 5.1.6 on 2025-04-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_slug',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='business',
            name='business_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='business_images/', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='business_images/', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='business_images/', verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='business_images/', verbose_name='Image 4'),
        ),
    ]
