# Generated by Django 5.1.6 on 2025-04-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_advertisement_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
