# Generated by Django 5.1.6 on 2025-04-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_business_business_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_website',
            field=models.URLField(blank=True, null=True, verbose_name='Website Link'),
        ),
    ]
