# Generated by Django 5.1.6 on 2025-04-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_business_business_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logo/', verbose_name='business logo'),
        ),
    ]
