# Generated by Django 5.1.6 on 2025-05-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_business_business_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ZodiacDailyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('aries', models.CharField(max_length=255)),
                ('taurus', models.CharField(max_length=255)),
                ('gemini', models.CharField(max_length=255)),
                ('cancer', models.CharField(max_length=255)),
                ('leo', models.CharField(max_length=255)),
                ('virgo', models.CharField(max_length=255)),
                ('libra', models.CharField(max_length=255)),
                ('scorpio', models.CharField(max_length=255)),
                ('sagittarius', models.CharField(max_length=255)),
                ('capricorn', models.CharField(max_length=255)),
                ('aquarius', models.CharField(max_length=255)),
                ('pisces', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
