# Generated by Django 5.2.1 on 2025-05-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_payment_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poojabooking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
