# Generated by Django 5.2.1 on 2025-06-17 09:59

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_poojabooking_razorpay_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(upload_to='business_blog_images/', verbose_name='Banner Image')),
                ('content', tinymce.models.HTMLField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('business_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Business Category')),
            ],
        ),
    ]
